# Generated by Django 5.2.14 on 2026-05-18 15:55

import django.db.models.deletion
import django.utils.timezone
import meetings.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('recording', 'Recording'), ('ended', 'Ended'), ('complete', 'Complete'), ('failed', 'Failed')], default='recording', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AudioSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_segment_id', models.CharField(blank=True, max_length=80)),
                ('sequence_number', models.PositiveIntegerField()),
                ('speaker_label', models.CharField(max_length=64)),
                ('speaker_confidence', models.FloatField(blank=True, null=True)),
                ('client_start_ms', models.PositiveBigIntegerField()),
                ('client_end_ms', models.PositiveBigIntegerField()),
                ('codec', models.CharField(blank=True, max_length=32)),
                ('sample_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('audio_file', models.FileField(upload_to=meetings.models.segment_upload_path)),
                ('audio_content_type', models.CharField(blank=True, max_length=120)),
                ('audio_size_bytes', models.PositiveIntegerField(default=0)),
                ('transcription_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('transcription_text', models.TextField(blank=True)),
                ('transcription_model', models.CharField(blank=True, max_length=80)),
                ('transcription_response', models.JSONField(blank=True, default=dict)),
                ('transcription_attempts', models.PositiveIntegerField(default=0)),
                ('transcription_started_at', models.DateTimeField(blank=True, null=True)),
                ('transcribed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_segments', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='meetings.meeting')),
            ],
            options={
                'ordering': ['meeting__started_at', 'meeting_id', 'sequence_number'],
                'indexes': [models.Index(fields=['transcription_status', 'created_at'], name='meetings_au_transcr_e063d3_idx'), models.Index(fields=['meeting', 'sequence_number'], name='meetings_au_meeting_4abb00_idx')],
                'constraints': [models.UniqueConstraint(fields=('meeting', 'sequence_number'), name='unique_segment_sequence_per_meeting')],
            },
        ),
    ]
