# Generated by Django 5.2.13 on 2026-05-18 21:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meeting_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='output_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='output_last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='output_model',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='meeting',
            name='output_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='meeting',
            name='output_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='meeting',
            name='title_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='title_model',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='meeting',
            name='title_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='MeetingMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_number', models.PositiveIntegerField()),
                ('speaker_label', models.CharField(blank=True, max_length=64)),
                ('client_start_ms', models.PositiveBigIntegerField(default=0)),
                ('client_end_ms', models.PositiveBigIntegerField(default=0)),
                ('transcript_text', models.TextField()),
                ('detailed_summary', models.TextField(blank=True)),
                ('short_summary', models.CharField(blank=True, max_length=180)),
                ('detailed_summary_response', models.JSONField(blank=True, default=dict)),
                ('short_summary_response', models.JSONField(blank=True, default=dict)),
                ('summary_model', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='meetings.meeting')),
                ('segments', models.ManyToManyField(blank=True, related_name='display_messages', to='meetings.audiosegment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['meeting__started_at', 'meeting_id', 'sequence_number'],
                'indexes': [models.Index(fields=['meeting', 'sequence_number'], name='meetings_me_meeting_00e268_idx')],
                'constraints': [models.UniqueConstraint(fields=('meeting', 'sequence_number'), name='unique_message_sequence_per_meeting')],
            },
        ),
    ]
