# Generated by Django 5.2.13 on 2026-05-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_meeting_output_generated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(blank=True, choices=[('requirement_gathering', 'Requirement gathering'), ('requirement_gathering_minutes', 'Requirement gathering minutes'), ('followup_meeting', 'Followup meeting'), ('draft_delivery', 'Draft delivery')], max_length=32),
        ),
    ]
