# Generated by Django 5.2.13 on 2026-05-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_meetingimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingimport',
            name='progress_message',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='meetingimport',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
