# Generated by Django 5.2.13 on 2026-05-21 15:23

from django.db import migrations, models


def mark_existing_generated_minutes_complete(apps, schema_editor):
    Meeting = apps.get_model('meetings', 'Meeting')
    Meeting.objects.filter(minutes_generated_at__isnull=False).update(minutes_status='complete')
    Meeting.objects.filter(minutes_generated_at__isnull=True, minutes_last_error__gt='').update(minutes_status='failed')


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_alter_meeting_meeting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='minutes_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='minutes_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='minutes_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='idle', max_length=16),
        ),
        migrations.RunPython(mark_existing_generated_minutes_complete, migrations.RunPython.noop),
    ]
