# Generated by Django 5.2.13 on 2026-05-24 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_settings_for_existing_users(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)
    UserWebSettings = apps.get_model("meetings", "UserWebSettings")
    existing_user_ids = set(UserWebSettings.objects.values_list("user_id", flat=True))
    UserWebSettings.objects.bulk_create(
        UserWebSettings(user_id=user_id, force_password_change=True)
        for user_id in User.objects.exclude(id__in=existing_user_ids).values_list("id", flat=True)
    )


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_meeting_minutes_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWebSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force_password_change', models.BooleanField(default=True)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='web_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user web settings',
                'verbose_name_plural': 'user web settings',
            },
        ),
        migrations.RunPython(create_settings_for_existing_users, migrations.RunPython.noop),
    ]
