# Generated by Django 5.2.13 on 2026-05-25 08:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


def copy_existing_minutes(apps, schema_editor):
    Meeting = apps.get_model("meetings", "Meeting")
    MeetingMinutesOutput = apps.get_model("meetings", "MeetingMinutesOutput")
    outputs = []
    for meeting in Meeting.objects.exclude(meeting_type="").iterator():
        if not (
            meeting.minutes_text
            or meeting.minutes_model
            or meeting.minutes_last_error
            or meeting.minutes_status != "idle"
        ):
            continue
        outputs.append(
            MeetingMinutesOutput(
                meeting_id=meeting.id,
                meeting_type=meeting.meeting_type,
                text=meeting.minutes_text,
                model=meeting.minutes_model,
                response=meeting.minutes_response,
                status=meeting.minutes_status,
                requested_at=meeting.minutes_requested_at,
                started_at=meeting.minutes_started_at,
                generated_at=meeting.minutes_generated_at,
                last_error=meeting.minutes_last_error,
            )
        )
    MeetingMinutesOutput.objects.bulk_create(outputs, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0009_user_web_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(blank=True, choices=[('requirement_gathering', 'Requirement gathering'), ('requirement_gathering_minutes', 'Requirement gathering minutes'), ('followup_meeting', 'Followup meeting'), ('draft_delivery', 'Draft delivery'), ('project_manager_notes', 'Project manager notes'), ('lujy_pm_notes', 'Lujy PM notes')], max_length=32),
        ),
        migrations.CreateModel(
            name='MeetingMinutesOutput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meeting_type', models.CharField(choices=[('requirement_gathering', 'Requirement gathering'), ('requirement_gathering_minutes', 'Requirement gathering minutes'), ('followup_meeting', 'Followup meeting'), ('draft_delivery', 'Draft delivery'), ('project_manager_notes', 'Project manager notes'), ('lujy_pm_notes', 'Lujy PM notes')], max_length=32)),
                ('text', models.TextField(blank=True)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='idle', max_length=16)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minutes_outputs', to='meetings.meeting')),
            ],
            options={
                'ordering': ['-generated_at', '-updated_at'],
                'indexes': [models.Index(fields=['status', 'requested_at'], name='meetings_me_status_906d0a_idx'), models.Index(fields=['meeting', 'meeting_type'], name='meetings_me_meeting_e28938_idx')],
                'constraints': [models.UniqueConstraint(fields=('meeting', 'meeting_type'), name='unique_minutes_output_per_meeting_type')],
            },
        ),
        migrations.RunPython(copy_existing_minutes, migrations.RunPython.noop),
    ]
