# Generated by Django 5.2.14 on 2026-06-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0010_minutes_outputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwebsettings',
            name='can_view_all_meetings',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(blank=True, choices=[('requirement_gathering', 'Requirement gathering'), ('requirement_gathering_minutes', 'Requirement gathering minutes'), ('followup_meeting', 'Followup meeting'), ('draft_delivery', 'Draft delivery'), ('project_manager_notes', 'Project manager notes'), ('meeting_health_report', 'Meeting health report'), ('compact_pm_notes', 'Compact PM notes')], max_length=32),
        ),
        migrations.AlterField(
            model_name='meetingminutesoutput',
            name='meeting_type',
            field=models.CharField(choices=[('requirement_gathering', 'Requirement gathering'), ('requirement_gathering_minutes', 'Requirement gathering minutes'), ('followup_meeting', 'Followup meeting'), ('draft_delivery', 'Draft delivery'), ('project_manager_notes', 'Project manager notes'), ('meeting_health_report', 'Meeting health report'), ('compact_pm_notes', 'Compact PM notes')], max_length=32),
        ),
    ]
